// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(IskolaDbContext))]
    [Migration("20250826190303_KezdoEvAdded")]
    partial class KezdoEvAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Data.Osztaly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Betu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EvFolyam")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KezdoEv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OsztalyFonok")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Osztalyok", (string)null);
                });

            modelBuilder.Entity("Data.Tanulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GyermekVedelmi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HalmozottanHatranyos")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Hatranyos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OsztalyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OsztalyId");

                    b.ToTable("Tanulok", (string)null);
                });

            modelBuilder.Entity("Data.Tanulo", b =>
                {
                    b.HasOne("Data.Osztaly", "Osztaly")
                        .WithMany("Tanulok")
                        .HasForeignKey("OsztalyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osztaly");
                });

            modelBuilder.Entity("Data.Osztaly", b =>
                {
                    b.Navigation("Tanulok");
                });
#pragma warning restore 612, 618
        }
    }
}
